#cloud-config
runcmd:
 - sudo echo "#ubuntu" > /etc/apt/sources.list
 - sudo echo "deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse" >> /etc/apt/sources.list
 - sudo echo "deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse" >> /etc/apt/sources.list
 - sudo echo "deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse" >> /etc/apt/sources.list
 - sudo echo "deb http://archive.ubuntu.com/ubuntu focal-proposed restricted main universe multiverse" >> /etc/apt/sources.list
 - sudo echo "#security" >> /etc/apt/sources.list
 - sudo echo "deb http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse" >> /etc/apt/sources.list
 - sudo echo "#partner" >> /etc/apt/sources.list
 - sudo echo "deb http://archive.canonical.com/ubuntu focal partner" >> /etc/apt/sources.list
 - sudo echo "DEBIAN_FRONTEND=noninteractive" >> /etc/environment
 - sudo source /etc/environment && source /etc/environment
 - sudo apt update --fix-missing
 - sudo apt -y install apt-transport-https bash-completion ca-certificates conntrack curl ethtool htop ipset mlocate nano net-tools nftables socat software-properties-common tar unzip wget xz-utils
 - sudo echo "#docker" > /etc/apt/sources.list.d/docker.list
 - sudo echo "deb https://download.docker.com/linux/ubuntu focal stable" >> /etc/apt/sources.list.d/docker.list
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7EA0A9C3F273FCD8
 - sudo echo "#kubernetes" > /etc/apt/sources.list.d/kubernetes.list
 - sudo echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" >> /etc/apt/sources.list.d/kubernetes.list
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 6A030B21BA07F4FB
 - sudo apt update --fix-missing
 - sudo apt -y install containerd.io=1.2.13-2 kubeadm=1.18.6-00 kubelet=1.18.6-00 kubectl=1.18.6-00
 - sudo apt-mark hold containerd.io=1.2.13-2 kubeadm=1.18.6-00 kubelet=1.18.6-00 kubectl=1.18.6-00
 - sudo mkdir -p /etc/containerd && sudo containerd config default > /etc/containerd/config.toml
 - sudo usermod -aG docker ${USER}
 - sudo systemctl daemon-reload
 - sudo systemctl enable containerd && sudo systemctl start containerd
 - sudo systemctl enable kubelet && sudo systemctl start kubelet
 - sudo swapoff -a
